name: Typescript
on:
  push:
    branches: [ daddy ]
  pull_request:
    branches: [ daddy ]
permissions:
  contents: read
jobs:
  warnings:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Check Typescript Warnings
      run: npx tsc --noEmit --jsx preserve
